[2025-06-16T22:02:47.330+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:02:47.331+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:02:47.333+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:02:47.332+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:02:47.376+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:02:47.369+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:02:47.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:02:47.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.115 seconds
[2025-06-16T22:03:17.934+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:03:17.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:03:17.938+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:03:17.937+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:03:17.987+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:03:17.980+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:03:17.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:03:18.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.143 seconds
[2025-06-16T22:03:48.939+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:03:48.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:03:48.943+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:03:48.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:03:48.976+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:03:48.970+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:03:48.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:03:49.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.097 seconds
[2025-06-16T22:04:19.152+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:04:19.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:04:19.155+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:04:19.155+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:04:19.182+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:04:19.178+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:04:19.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:04:19.236+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.087 seconds
[2025-06-16T22:04:49.659+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:04:49.660+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:04:49.662+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:04:49.661+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:04:49.695+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:04:49.687+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:04:49.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:04:49.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.097 seconds
[2025-06-16T22:05:20.059+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:05:20.060+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:05:20.062+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:05:20.061+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:05:20.088+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:05:20.084+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:05:20.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:05:20.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.086 seconds
[2025-06-16T22:05:50.545+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:05:50.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:05:50.548+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:05:50.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:05:50.572+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:05:50.568+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:05:50.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:05:50.624+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.082 seconds
[2025-06-16T22:06:20.921+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:06:20.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:06:20.924+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:06:20.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:06:20.961+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:06:20.954+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:06:20.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:06:21.011+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.095 seconds
[2025-06-16T22:06:51.293+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:06:51.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:06:51.296+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:06:51.296+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:06:51.322+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:06:51.318+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:06:51.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:06:51.377+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.087 seconds
[2025-06-16T22:07:21.870+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:07:21.871+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:07:21.872+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:07:21.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:07:21.897+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:07:21.893+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:07:21.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:07:21.953+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.087 seconds
[2025-06-16T22:07:52.765+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:07:52.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:07:52.768+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:07:52.767+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:07:52.794+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:07:52.790+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:07:52.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:07:52.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.098 seconds
[2025-06-16T22:08:23.657+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:08:23.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:08:23.660+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:08:23.659+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:08:23.688+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:08:23.683+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:08:23.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:08:23.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.091 seconds
[2025-06-16T22:08:54.620+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:08:54.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:08:54.623+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:08:54.622+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:08:54.657+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:08:54.651+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:08:54.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:08:54.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.103 seconds
[2025-06-16T22:09:25.555+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:09:25.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:09:25.559+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:09:25.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:09:25.588+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:09:25.580+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:09:25.590+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:09:25.643+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.090 seconds
[2025-06-16T22:09:56.473+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:09:56.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:09:56.476+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:09:56.476+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:09:56.502+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:09:56.498+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:09:56.504+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:09:56.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.087 seconds
[2025-06-16T22:10:27.295+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:10:27.296+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:10:27.297+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:10:27.297+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:10:27.321+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:10:27.317+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:10:27.323+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:10:27.377+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.085 seconds
[2025-06-16T22:10:58.210+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:10:58.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:10:58.214+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:10:58.213+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:10:58.247+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:10:58.241+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:10:58.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:10:58.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.091 seconds
[2025-06-16T22:11:29.349+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:11:29.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:11:29.352+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:11:29.351+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:11:29.386+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:11:29.381+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:11:29.389+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:11:29.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.085 seconds
[2025-06-16T22:12:00.133+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:12:00.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:12:00.136+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:12:00.135+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:12:00.161+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:12:00.156+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:12:00.163+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:12:00.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.084 seconds
[2025-06-16T22:12:31.201+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:12:31.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:12:31.204+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:12:31.203+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:12:31.231+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:12:31.226+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:12:31.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:12:31.301+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.104 seconds
[2025-06-16T22:13:01.952+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:13:01.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:13:01.955+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:13:01.954+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:13:01.984+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:13:01.978+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:13:01.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:13:02.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.093 seconds
[2025-06-16T22:13:32.954+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:13:32.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:13:32.957+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:13:32.957+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:13:32.987+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:13:32.982+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:13:32.989+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:13:33.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.097 seconds
[2025-06-16T22:14:03.874+0000] {processor.py:161} INFO - Started process (PID=123) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:14:03.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:14:03.876+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:14:03.876+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:14:03.907+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:14:03.902+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:14:03.909+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:14:03.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.097 seconds
[2025-06-16T22:14:34.768+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:14:34.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:14:34.771+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:14:34.770+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:14:34.801+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:14:34.796+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T22:14:34.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:14:34.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.078 seconds
[2025-06-16T22:15:05.721+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:15:05.723+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:15:05.724+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:15:05.724+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:15:07.136+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:15:07.344+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:15:07.343+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:etl_cassandra_to_clickhouse
[2025-06-16T22:15:07.388+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:15:07.388+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:etl_cassandra_to_clickhouse
[2025-06-16T22:15:07.422+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:15:07.422+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:etl_cassandra_to_clickhouse
[2025-06-16T22:15:07.424+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:15:07.423+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:15:07.446+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:15:07.446+0000] {dag.py:3058} INFO - Creating ORM DAG for etl_cassandra_to_clickhouse
[2025-06-16T22:15:07.462+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:15:07.462+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:15:07.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.831 seconds
[2025-06-16T22:15:38.025+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:15:38.026+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:15:38.027+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:15:38.027+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:15:38.845+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:15:38.874+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:15:38.874+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:15:38.906+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:15:38.906+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:15:38.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.953 seconds
[2025-06-16T22:16:09.314+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:16:09.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:16:09.316+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:16:09.316+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:16:10.391+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:16:10.436+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:16:10.436+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:16:10.469+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:16:10.469+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:16:10.559+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.248 seconds
[2025-06-16T22:29:09.145+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:29:09.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:29:09.149+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:29:09.148+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:29:10.017+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:29:10.063+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:29:10.062+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:29:10.123+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:29:10.122+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:29:10.226+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.084 seconds
[2025-06-16T22:29:40.947+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:29:40.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:29:40.950+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:29:40.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:29:41.803+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:29:41.835+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:29:41.834+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:29:41.866+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:29:41.865+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:29:41.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.007 seconds
[2025-06-16T22:30:13.064+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:30:13.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:30:13.067+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:30:13.067+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:30:13.889+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:30:13.919+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:30:13.919+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:30:13.956+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:30:13.956+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:30:14.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.971 seconds
[2025-06-16T22:30:44.247+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:30:44.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:30:44.250+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:30:44.249+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:30:45.078+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:30:45.109+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:30:45.109+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:30:45.142+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:30:45.141+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:30:45.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.980 seconds
[2025-06-16T22:31:16.220+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:31:16.222+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:31:16.225+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:31:16.224+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:31:17.067+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:31:17.097+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:31:17.097+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:31:17.129+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:31:17.129+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:31:17.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.994 seconds
[2025-06-16T22:31:48.399+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:31:48.400+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:31:48.402+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:31:48.401+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:31:49.300+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:31:49.330+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:31:49.330+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:31:49.373+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:31:49.373+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:31:49.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.071 seconds
[2025-06-16T22:32:19.721+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:32:19.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:32:19.723+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:32:19.723+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:32:20.590+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:32:20.619+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:32:20.619+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:32:20.651+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:32:20.651+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:32:20.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.011 seconds
[2025-06-16T22:32:51.124+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:32:51.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:32:51.126+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:32:51.126+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:32:52.010+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:32:52.041+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:32:52.040+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:32:52.071+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:32:52.071+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:32:52.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.026 seconds
[2025-06-16T22:33:22.421+0000] {processor.py:161} INFO - Started process (PID=90) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:33:22.423+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:33:22.424+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:33:22.424+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:33:23.301+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:33:23.340+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:33:23.339+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:33:23.378+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:33:23.378+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:33:23.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.068 seconds
[2025-06-16T22:33:53.855+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:33:53.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:33:53.858+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:33:53.858+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:33:54.745+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:33:54.774+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:33:54.774+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:33:54.805+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:33:54.805+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:33:54.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.034 seconds
[2025-06-16T22:34:25.372+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:34:25.374+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:34:25.376+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:34:25.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:34:26.413+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:34:26.442+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:34:26.442+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:34:26.476+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:34:26.475+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:34:26.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.201 seconds
[2025-06-16T22:34:56.863+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:34:56.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:34:56.866+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:34:56.866+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:34:57.714+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:34:57.743+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:34:57.743+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:34:57.773+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:34:57.773+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:34:57.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.979 seconds
[2025-06-16T22:35:28.212+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:35:28.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:35:28.214+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:35:28.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:35:29.069+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:35:29.101+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:35:29.100+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:35:29.132+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:35:29.132+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:35:29.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.013 seconds
[2025-06-16T22:35:59.621+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:35:59.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:35:59.623+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:35:59.623+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:36:00.562+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:36:00.604+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:36:00.604+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:36:00.633+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:36:00.633+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:36:00.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.088 seconds
[2025-06-16T22:36:31.180+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:36:31.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:36:31.184+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:36:31.184+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:36:32.060+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:36:32.091+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:36:32.090+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:36:32.124+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:36:32.123+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:36:32.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.020 seconds
[2025-06-16T22:37:02.623+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:37:02.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:37:02.626+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:37:02.626+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:37:03.444+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:37:03.473+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:37:03.472+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:37:03.504+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:37:03.503+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:37:03.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.960 seconds
[2025-06-16T22:37:33.894+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:37:33.896+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:37:33.897+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:37:33.897+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:37:34.663+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:37:34.700+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:37:34.699+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:37:34.731+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:37:34.731+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:37:34.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.923 seconds
[2025-06-16T22:38:05.028+0000] {processor.py:161} INFO - Started process (PID=123) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:38:05.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:38:05.031+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:38:05.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:38:05.924+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:38:05.959+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:38:05.958+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:38:05.993+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:38:05.993+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:38:06.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.052 seconds
[2025-06-16T22:38:36.413+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:38:36.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:38:36.416+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:38:36.416+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:38:37.300+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:38:37.329+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:38:37.328+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:38:37.361+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:38:37.360+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:38:37.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.035 seconds
[2025-06-16T22:39:07.813+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:39:07.814+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:39:07.815+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:39:07.815+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:39:08.624+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:39:08.656+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:39:08.656+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:39:08.690+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:39:08.689+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:39:08.773+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.965 seconds
[2025-06-16T22:39:39.123+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:39:39.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:39:39.125+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:39:39.125+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:39:40.082+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:39:40.122+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:39:40.121+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:39:40.166+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:39:40.166+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:39:40.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.138 seconds
[2025-06-16T22:40:10.649+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:40:10.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:40:10.653+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:40:10.652+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:40:11.580+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:40:11.619+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:40:11.619+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:40:11.661+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:40:11.661+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-17 00:00:00+00:00, run_after=2025-06-18 00:00:00+00:00
[2025-06-16T22:40:11.760+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.116 seconds
[2025-06-16T22:40:27.028+0000] {processor.py:161} INFO - Started process (PID=153) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:40:27.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T22:40:27.031+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:40:27.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:40:28.008+0000] {processor.py:840} INFO - DAG(s) 'etl_cassandra_to_clickhouse' retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T22:40:28.180+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:40:28.179+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-06-16T22:40:28.215+0000] {logging_mixin.py:188} INFO - [2025-06-16T22:40:28.214+0000] {dag.py:3823} INFO - Setting next_dagrun for etl_cassandra_to_clickhouse to 2025-06-15 00:00:00+00:00, run_after=2025-06-16 00:00:00+00:00
[2025-06-16T22:40:28.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 1.279 seconds
[2025-06-16T23:12:28.364+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:12:28.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:12:28.366+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:12:28.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:12:28.389+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:12:28.384+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:12:28.391+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:12:28.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.063 seconds
[2025-06-16T23:12:58.649+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:12:58.650+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:12:58.652+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:12:58.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:12:58.680+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:12:58.674+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:12:58.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:12:58.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.070 seconds
[2025-06-16T23:13:28.940+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:13:28.941+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:13:28.943+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:13:28.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:13:28.972+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:13:28.966+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:13:28.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:13:29.000+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.064 seconds
[2025-06-16T23:13:59.224+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:13:59.226+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:13:59.227+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:13:59.227+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:13:59.259+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:13:59.254+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:13:59.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:13:59.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.070 seconds
[2025-06-16T23:14:29.532+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:14:29.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:14:29.534+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:14:29.534+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:14:29.563+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:14:29.558+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:14:29.565+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:14:29.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.063 seconds
[2025-06-16T23:14:59.832+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:14:59.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:14:59.834+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:14:59.834+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:14:59.867+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:14:59.860+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:14:59.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:14:59.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.070 seconds
[2025-06-16T23:15:30.161+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:15:30.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:15:30.164+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:15:30.163+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:15:30.192+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:15:30.187+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:15:30.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:15:30.230+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.074 seconds
[2025-06-16T23:16:00.427+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:16:00.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:16:00.429+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:16:00.429+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:16:00.457+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:16:00.453+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:16:00.459+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:16:00.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.066 seconds
[2025-06-16T23:16:30.728+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:16:30.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:16:30.730+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:16:30.729+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:16:30.754+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:16:30.750+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:16:30.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:16:30.792+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.069 seconds
[2025-06-16T23:17:00.991+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:17:00.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:17:00.993+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:17:00.993+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:17:01.022+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:17:01.016+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:17:01.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:17:01.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.067 seconds
[2025-06-16T23:17:31.368+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:17:31.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:17:31.370+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:17:31.369+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:17:31.396+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:17:31.390+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:17:31.398+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:17:31.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.064 seconds
[2025-06-16T23:18:01.701+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:18:01.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:18:01.703+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:18:01.703+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:18:01.732+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:18:01.727+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:18:01.735+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:18:01.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.066 seconds
[2025-06-16T23:18:32.077+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:18:32.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:18:32.080+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:18:32.079+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:18:32.115+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:18:32.110+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:18:32.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:18:32.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.080 seconds
[2025-06-16T23:19:02.304+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:19:02.305+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:19:02.306+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:19:02.306+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:19:02.334+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:19:02.329+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:19:02.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:19:02.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.064 seconds
[2025-06-16T23:19:36.451+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:19:36.453+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:19:36.454+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:19:36.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:19:36.477+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:19:36.472+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:19:36.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:19:36.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.059 seconds
[2025-06-16T23:20:06.731+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:20:06.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:20:06.735+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:20:06.734+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:20:06.793+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:20:06.787+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:20:06.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:20:06.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.100 seconds
[2025-06-16T23:20:37.197+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:20:37.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:20:37.199+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:20:37.199+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:20:37.226+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:20:37.222+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:20:37.228+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:20:37.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.063 seconds
[2025-06-16T23:21:07.437+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:21:07.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:21:07.439+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:21:07.439+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:21:07.460+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:21:07.456+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:21:07.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:21:07.488+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.055 seconds
[2025-06-16T23:21:37.760+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:21:37.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:21:37.763+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:21:37.763+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:21:37.794+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:21:37.789+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:21:37.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:21:37.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.070 seconds
[2025-06-16T23:22:08.094+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:22:08.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:22:08.097+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:22:08.097+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:22:08.121+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:22:08.116+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:22:08.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:22:08.157+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.067 seconds
[2025-06-16T23:22:38.376+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:22:38.377+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:22:38.378+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:22:38.377+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:22:38.400+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:22:38.396+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:22:38.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:22:38.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.061 seconds
[2025-06-16T23:23:08.704+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:23:08.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:23:08.707+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:23:08.707+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:23:08.742+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:23:08.736+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:23:08.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:23:08.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.075 seconds
[2025-06-16T23:23:39.146+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:23:39.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:23:39.148+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:23:39.148+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:23:39.173+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:23:39.168+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:23:39.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:23:39.207+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.065 seconds
[2025-06-16T23:24:09.521+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:24:09.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:24:09.524+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:24:09.523+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:24:09.550+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:24:09.545+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:24:09.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:24:09.581+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.064 seconds
[2025-06-16T23:24:39.931+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:24:39.933+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:24:39.935+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:24:39.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:24:39.965+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:24:39.960+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:24:39.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:24:40.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.074 seconds
[2025-06-16T23:25:10.158+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:25:10.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:25:10.161+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:25:10.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:25:10.191+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:25:10.185+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:25:10.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:25:10.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.065 seconds
[2025-06-16T23:25:40.436+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:25:40.437+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:25:40.438+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:25:40.438+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:25:40.464+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:25:40.460+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:25:40.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:25:40.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.061 seconds
[2025-06-16T23:26:10.760+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:26:10.761+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:26:10.762+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:26:10.762+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:26:10.786+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:26:10.781+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:26:10.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:26:10.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.064 seconds
[2025-06-16T23:26:41.011+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:26:41.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:26:41.014+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:26:41.013+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:26:41.043+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:26:41.037+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:26:41.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:26:41.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.071 seconds
[2025-06-16T23:27:11.354+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:27:11.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:27:11.356+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:27:11.356+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:27:11.381+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:27:11.376+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:27:11.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:27:11.412+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.060 seconds
[2025-06-16T23:27:41.721+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:27:41.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:27:41.723+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:27:41.723+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:27:41.749+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:27:41.744+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:27:41.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:27:41.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.065 seconds
[2025-06-16T23:28:12.029+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:28:12.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:28:12.031+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:28:12.031+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:28:12.655+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:28:12.648+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:28:12.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:28:12.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.657 seconds
[2025-06-16T23:28:42.976+0000] {processor.py:161} INFO - Started process (PID=287) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:28:42.977+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:28:42.979+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:28:42.978+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:28:43.315+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:28:43.309+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:28:43.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:28:43.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.383 seconds
[2025-06-16T23:29:13.480+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:29:13.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:29:13.483+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:29:13.482+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:29:13.809+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:29:13.802+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:29:13.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:29:13.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.363 seconds
[2025-06-16T23:29:44.091+0000] {processor.py:161} INFO - Started process (PID=297) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:29:44.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:29:44.093+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:29:44.093+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:29:44.423+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:29:44.418+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:29:44.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:29:44.450+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.363 seconds
[2025-06-16T23:30:15.502+0000] {processor.py:161} INFO - Started process (PID=302) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:30:15.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:30:15.506+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:30:15.506+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:30:15.939+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:30:15.932+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:30:15.942+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:30:15.987+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.490 seconds
[2025-06-16T23:30:46.302+0000] {processor.py:161} INFO - Started process (PID=307) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:30:46.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:30:46.305+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:30:46.304+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:30:46.726+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:30:46.719+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:30:46.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:30:46.760+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.464 seconds
[2025-06-16T23:31:17.148+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:31:17.149+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:31:17.150+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:31:17.150+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:31:17.572+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:31:17.566+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:31:17.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:31:17.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.470 seconds
[2025-06-16T23:31:47.790+0000] {processor.py:161} INFO - Started process (PID=317) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:31:47.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:31:47.793+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:31:47.793+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:31:48.226+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:31:48.220+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:31:48.228+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:31:48.254+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.468 seconds
[2025-06-16T23:32:18.564+0000] {processor.py:161} INFO - Started process (PID=322) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:32:18.566+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:32:18.567+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:32:18.567+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:32:18.978+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:32:18.972+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:32:18.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:32:19.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.461 seconds
[2025-06-16T23:32:49.384+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:32:49.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:32:49.386+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:32:49.386+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:32:49.768+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:32:49.762+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:32:49.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:32:49.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.417 seconds
[2025-06-16T23:33:20.076+0000] {processor.py:161} INFO - Started process (PID=332) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:33:20.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:33:20.079+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:33:20.078+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:33:20.462+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:33:20.456+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:33:20.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:33:20.509+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.436 seconds
[2025-06-16T23:33:50.963+0000] {processor.py:161} INFO - Started process (PID=337) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:33:50.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:33:50.966+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:33:50.965+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:33:51.302+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:33:51.296+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:33:51.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:33:51.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.776 seconds
[2025-06-16T23:34:22.077+0000] {processor.py:161} INFO - Started process (PID=342) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:34:22.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:34:22.080+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:34:22.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:34:22.419+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:34:22.413+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:34:22.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:34:22.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.382 seconds
[2025-06-16T23:34:52.777+0000] {processor.py:161} INFO - Started process (PID=347) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:34:52.778+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:34:52.779+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:34:52.779+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:34:53.163+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:34:53.155+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:34:53.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:34:53.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.440 seconds
[2025-06-16T23:35:23.545+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:35:23.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:35:23.547+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:35:23.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:35:23.900+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:35:23.893+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:35:23.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:35:23.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.388 seconds
[2025-06-16T23:35:54.197+0000] {processor.py:161} INFO - Started process (PID=357) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:35:54.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:35:54.199+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:35:54.199+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:35:54.579+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:35:54.573+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:35:54.582+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:35:54.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.420 seconds
[2025-06-16T23:36:24.925+0000] {processor.py:161} INFO - Started process (PID=362) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:36:24.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:36:24.928+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:36:24.927+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:36:25.535+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:36:25.528+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:36:25.537+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:36:25.586+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.666 seconds
[2025-06-16T23:36:55.688+0000] {processor.py:161} INFO - Started process (PID=367) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:36:55.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:36:55.691+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:36:55.690+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:36:56.053+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:36:56.047+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:36:56.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:36:56.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.412 seconds
[2025-06-16T23:37:26.443+0000] {processor.py:161} INFO - Started process (PID=372) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:37:26.444+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:37:26.446+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:37:26.445+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:37:26.838+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:37:26.832+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:37:26.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:37:26.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.429 seconds
[2025-06-16T23:37:57.214+0000] {processor.py:161} INFO - Started process (PID=377) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:37:57.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:37:57.217+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:37:57.216+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:37:57.652+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:37:57.646+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:37:57.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:37:57.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.477 seconds
[2025-06-16T23:38:28.054+0000] {processor.py:161} INFO - Started process (PID=382) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:38:28.055+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:38:28.057+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:38:28.057+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:38:28.473+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:38:28.467+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:38:28.475+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:38:28.501+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.451 seconds
[2025-06-16T23:38:58.778+0000] {processor.py:161} INFO - Started process (PID=387) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:38:58.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:38:58.780+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:38:58.780+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:38:59.183+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:38:59.176+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:38:59.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:38:59.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.445 seconds
[2025-06-16T23:39:29.528+0000] {processor.py:161} INFO - Started process (PID=392) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:39:29.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:39:29.531+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:39:29.530+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:39:29.871+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:39:29.865+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:39:29.873+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:39:29.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.380 seconds
[2025-06-16T23:40:00.192+0000] {processor.py:161} INFO - Started process (PID=397) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:40:00.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:40:00.196+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:40:00.196+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:40:00.527+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:40:00.522+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:40:00.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:40:00.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.371 seconds
[2025-06-16T23:40:30.833+0000] {processor.py:161} INFO - Started process (PID=402) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:40:30.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:40:30.836+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:40:30.836+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:40:31.221+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:40:31.214+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:40:31.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:40:31.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.432 seconds
[2025-06-16T23:41:12.580+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:41:12.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:41:12.582+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:41:12.582+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:41:12.603+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:41:12.598+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:41:12.605+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:41:12.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.052 seconds
[2025-06-16T23:41:42.862+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:41:42.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:41:42.865+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:41:42.865+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:41:42.906+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:41:42.901+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:41:42.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:41:42.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.082 seconds
[2025-06-16T23:42:13.105+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:42:13.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:42:13.107+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:42:13.107+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:42:13.131+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:42:13.127+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:42:13.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:42:13.159+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.058 seconds
[2025-06-16T23:42:43.412+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:42:43.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:42:43.415+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:42:43.414+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:42:43.447+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:42:43.440+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:42:43.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:42:43.490+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.081 seconds
[2025-06-16T23:43:13.674+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:43:13.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:43:13.676+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:43:13.676+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:43:13.703+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:43:13.698+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:43:13.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:43:13.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.063 seconds
[2025-06-16T23:43:44.022+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:43:44.023+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:43:44.024+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:43:44.024+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:43:44.055+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:43:44.049+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:43:44.057+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:43:44.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.068 seconds
[2025-06-16T23:44:14.257+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:44:14.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:44:14.259+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:44:14.259+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:44:14.281+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:44:14.277+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:44:14.283+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:44:14.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.063 seconds
[2025-06-16T23:44:44.518+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:44:44.519+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:44:44.521+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:44:44.520+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:44:44.550+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:44:44.545+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:44:44.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:44:44.584+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.069 seconds
[2025-06-16T23:45:14.888+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:45:14.890+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:45:14.892+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:45:14.891+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:45:15.564+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:45:15.558+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:45:15.566+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:45:15.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.717 seconds
[2025-06-16T23:45:52.567+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:45:52.568+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:45:52.570+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:45:52.569+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:45:52.937+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:45:52.931+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:45:52.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:45:52.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.402 seconds
[2025-06-16T23:46:23.262+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:46:23.263+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:46:23.265+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:46:23.264+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:46:23.678+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:46:23.671+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:46:23.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:46:23.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.467 seconds
[2025-06-16T23:46:54.125+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:46:54.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:46:54.128+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:46:54.128+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:46:54.473+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:46:54.467+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:46:54.475+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:46:54.508+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.387 seconds
[2025-06-16T23:47:24.756+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:47:24.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:47:24.759+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:47:24.759+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:47:25.171+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:47:25.166+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:47:25.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:47:25.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.451 seconds
[2025-06-16T23:47:55.519+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:47:55.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:47:55.523+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:47:55.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:47:56.112+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:47:56.107+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:47:56.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:47:56.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.628 seconds
[2025-06-16T23:48:26.408+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:48:26.410+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:48:26.412+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:48:26.411+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:48:26.819+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:48:26.812+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:48:26.821+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:48:26.855+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.452 seconds
[2025-06-16T23:48:57.189+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:48:57.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:48:57.192+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:48:57.192+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:48:57.604+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:48:57.597+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:48:57.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:48:57.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.450 seconds
[2025-06-16T23:49:27.973+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:49:27.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:49:27.976+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:49:27.976+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:49:28.362+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:49:28.358+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:49:28.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:49:28.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.428 seconds
[2025-06-16T23:49:58.731+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:49:58.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:49:58.734+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:49:58.733+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:49:59.050+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:49:59.045+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:49:59.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:49:59.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.353 seconds
[2025-06-16T23:50:29.440+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:50:29.442+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:50:29.444+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:50:29.443+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:50:29.901+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:50:29.895+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 6, in <module>
    from clickhouse_connect import get_client
ModuleNotFoundError: No module named 'clickhouse_connect'
[2025-06-16T23:50:29.903+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:50:29.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.497 seconds
[2025-06-16T23:51:23.581+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:51:23.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:51:23.585+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:51:23.584+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:51:23.608+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:51:23.603+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:51:23.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:51:23.637+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.061 seconds
[2025-06-16T23:51:53.846+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:51:53.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:51:53.849+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:51:53.848+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:51:53.873+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:51:53.868+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:51:53.875+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:51:53.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.064 seconds
[2025-06-16T23:52:24.165+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:52:24.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:52:24.167+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:52:24.167+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:52:24.191+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:52:24.187+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:52:24.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:52:24.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.066 seconds
[2025-06-16T23:52:54.400+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:52:54.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:52:54.402+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:52:54.402+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:52:54.427+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:52:54.422+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:52:54.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:52:54.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.061 seconds
[2025-06-16T23:53:24.745+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:53:24.746+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/cassandra_to_clickhouse_dag.py for tasks to queue
[2025-06-16T23:53:24.747+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:53:24.747+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:53:24.773+0000] {logging_mixin.py:188} INFO - [2025-06-16T23:53:24.769+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/cassandra_to_clickhouse_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cassandra_to_clickhouse_dag.py", line 5, in <module>
    from cassandra.cluster import Cluster
ModuleNotFoundError: No module named 'cassandra'
[2025-06-16T23:53:24.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/cassandra_to_clickhouse_dag.py
[2025-06-16T23:53:24.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/cassandra_to_clickhouse_dag.py took 0.063 seconds
